[package]
name = "clap-num"
version = "0.1.0"
authors = ["Alex M. <alexmgit@protonmail.com>"]
keywords = ["argument", "cli", "arg", "parser", "parse"]
categories = ["command-line-interface"]
description = "Number parsers for clap v3."
edition = "2018"
license = "MIT"

[dependencies]
num-traits = "0.2.12"

[dev-dependencies]
clap = "3.0.0-beta.1"
