[package]
name = "clap-validators"
version = "0.1.0"
authors = ["Alex M. <alexmgit@protonmail.com>"]
keywords = ["argument", "cli", "arg", "parser", "parse"]
categories = ["command-line-interface"]
description = "Validators for clap v3."
edition = "2018"
license = "MIT"

[dependencies]
clap = "3.0.0-beta.1"
